//AUTH
export const GET_AUTH_DATA = 'AUTH/GET_AUTH_DATA'  
export const SET_FETCHING_AUTH = 'AUTH/SET_FETCHING_AUTH'  
export const SET_PROFILE_PHOTO = 'AUTH/SET_PROFILE_PHOTO'  
export const LOGOUT_USER = 'AUTH/LOGOUT_USER'  
//profile
export const GET_PROFILE_DATA = 'PROFILE/GET_PROFILE_DATA'
export const SET_FETCHING_PROFILE_DATA = 'PROFILE/SET_FETCHING_PROFILE_DATA'
export const SET_PROFILE_STATUS = 'PROFILE/SET_PROFILE_STATUS'

//users
export const GET_USERS = 'USERS/GET_USERS'
export const SET_CURRENT_PAGE = 'USERS/SET_CURRENT_PAGE'
export const SET_FETCHING_USERS_DATA = 'USERS/SET_FETCHING_DATA'
export const FOLLOW_USER = 'USERS/FOLLOW_USER'
export const UNFOLLOW_USER = 'USERS/UNFOLLOW_USER'
export const SET_FOLLOWING_IN_PROGRESS_ID = 'USERS/SET_FOLLOWING_IN_PROGRESS_ID'
